cache:
  directories:
    - vendor
    - node_modules
    - bower_components

language: php

php:
  - 7.0

env:

before_install:
  - mysql -e 'CREATE DATABASE aenianos;'
  - composer install
  - ls -la /home/travis/build/SandroHc/Aenianos/bootstrap/
  - ls -la /home/travis/build/SandroHc/Aenianos/vendor/
  - npm install
  - php artisan migrate --seed