cache:
  directories:
    - vendor
    - node_modules

language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:

before_install:
  - mysql -e 'CREATE DATABASE aenianos;'
  - composer install
  - npm install
  - php artisan migrate --seed