cache:
  directories:
    - vendor
    - node_modules
    - bower_components

language: php

php:
  - 7.0

env:

before_install:
  - nvm install 4.2
  - mysql -e 'CREATE DATABASE aenianos;'
  - composer install
  - php artisan migrate --seed